---
- hosts: "jenkins"
  vars:
    temp_dir: "/tmp/chromedriver-build"
  become: yes
  become_method: sudo
  tasks:
    - name: clearing build dir
      file: path="{{temp_dir}}" state=absent

    - name: creating build dir
      file: path="{{temp_dir}}" state=directory

    - name: uploading build files
      synchronize: src=./ dest="{{temp_dir}}" perms=yes

    - name: building docker image
      command: make build chdir="{{temp_dir}}"

    - name: uploading chromedriver systemd service
      copy: src=chromedriver.service dest=/etc/systemd/system force=true

    - name: stopping chromedriver systemd service
      service: name=chromedriver state=stopped

    - name: reloading systemd
      command: systemctl daemon-reload

    - name: enabling chromedriver systemd service
      service: name=chromedriver enabled=true

    - name: restarting chromedriver systemd service
      service: name=chromedriver state=restarted
